version: '3.8'

services:
  # Python Worker only (uses cloud MongoDB)
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: babel-books-worker
    volumes:
      - ./worker:/app
      - /app/__pycache__
    env_file:
      - ./worker/.env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped