services:
  # Web Service
  - type: web
    name: babel-books-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_PRODUCT_NAME
        value: BabelBooks
      # Other env vars should be added via Render dashboard for security

  # Background Worker (Python)
  - type: worker
    name: babel-books-worker
    runtime: python
    buildCommand: cd worker && pip install -r requirements.txt
    startCommand: cd worker && uvicorn main_progressive:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      # Other env vars should be added via Render dashboard for security