services:
  # Web Service
  - type: web
    name: babel-books-web
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://babel-books.onrender.com
      - key: NEXT_PUBLIC_PRODUCT_NAME
        value: BabelBooks

  # Background Worker (Python)
  - type: worker
    name: babel-books-worker
    runtime: python
    buildCommand: cd worker && pip install -r requirements.txt
    startCommand: cd worker && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1